### PR TITLE
Update NAND Padgen

### LINKED ISSUE #1: NAND dump/decryption

### PR DESCRIPTION
**Pull request by swarzesherz**
Tested on 3DS and 3DS XL 9.2.0-20U fixes #1

### CODE REVIEW

**Comment by archshift** [comment]
Thanks for your contribution!

**Comment by archshift** [comment]
Did you ever manage to get an actual dump of NAND decrypted with this? I wasn't able to. If so, could you elaborate how you managed to do it?

In other words, how did you test this?

**Comment by swarzesherz** [comment]
To test use: https://gist.github.com/swarzesherz/651f69b2e8e5c370a0f4 with your nand or emunand
python 3DSFAT16tool.py -d NAND.bin NAND_fat16.iso nand.fat16.xorpad
To view contents of decripted NAND use WinImage or mount disc

**Comment by swarzesherz** [comment]
Sorry you need install requirements to xor work with only this script
1.- Install pip https://pip.pypa.io/en/latest/installing.html
2.- In command line: pip install numpy 
You can extract only your NAND_fat16.bin
https://gist.github.com/swarzesherz/651f69b2e8e5c370a0f4/d9b77da4b3a6d2ed909944c7d1e01d0ec6803296
python 3DSFAT16tool.py -d NAND.bin NAND_fat16.bin
And use to xor:
padxorer NAND_fat16.bin nand.fat16.xorpad

**Comment by swarzesherz** [comment]
Yo have acces to firm 8.x in sysnand?

**Comment by archshift** [comment]
Huh, that program worked. Interesting, and thanks.

**Pull request merged**
