### PR TITLE
Working on getting our forks merged again step #1

### PR DESCRIPTION
**Pull request by d0k3**
You may discard the earlier PR I sent, this is better. Also, sorry about the confusion, I'm learning to use Git and GitHub as I go.

### CODE REVIEW

**Comment by d0k3** [comment]
... and more. No new features up to this point. I tried to make the changes I did as easy to follow as possible.

**Comment by d0k3** [comment]
... and this is now up to date with my Brahma fork. Looking forward to hearing from you! The second step, if your wondering, is on my side, ie. actually merging my Brahma fork with your Bootstrap fork again. 

By the way, you may have already noticed, but the NAND dumper and NAND partitions dumper are not simply copy and paste from rxTools, but a clean rewrite.

**Comment by archshift** [comment]
If you don't mind, I went ahead and cherry-picked the commits manually while fixing them up along the way. A few things of note:
- I went through all the commits and changed the tabs back to spaces.
- I changed commit names to be more descriptive.
- I changed back a lot of the reordering you did of code. This makes the diffs much, much nicer to read.
- I fixed other misc code style issues.

**Comment by d0k3** [comment]
Alright, I'm just reviewing your changes and merging with my branch. I'm fine with most of the stuff you changed, but I have a few remarks...
- You reverted some of my changes to get rid of compiler warnings. Is there a reason why sdmmc.c should not be changed? Also, sdmmc_nand_readsectors() should be properly declared so that it can be used without the warning.
- Also, you put the goto: instruction back in. While there may be no real issues with it, using that is at least controverse. See for example here: http://www.drdobbs.com/jvm/programming-with-reason-why-is-goto-bad/228200966
- You moved the sha256.h / sha256.c back to the main source code directory, but I still think that is decryption related and should be kept with crypto.c and decryptor.c.
- The "decryptor/" prefix for including header files in decryptor.c is not needed, but if it is included there it should be included everywhere for consistency. That's not an issue now, but the old titlekey.c, f.e. didn't have the prefix.
- current_y in draw.h / draw.c should, to my understanding, not be extern, unless there is a reason to modify it from functions outside of draw.c. As draw.c should handle all the drawing, that shouldn't happen, though.
- The diffs are a lot nicer to read without the reorganization, but that opens a consistency issue. In decryptor.h either all or none of the "helper" (ie. non feature) functions should be declared. I think it's best to declare all if we do not reorganize the code.

And, yes, I know, a lot of the stuff above is nitpicking :).

Other than that, I agree that the coding style should be consistent. Using tabs instead of spaces is some kind of a personal quirk - I prefer tabs, the rest of the world seems to prefer spaces. I'll try to be more careful about that with future commits.

And, a small request (I know, this is not the place for requests usually): could you tell me how you manage to put the two commits for bootstrap compatibility always an top? Knowing that would be pretty useful for my Brahma fork.

**Pull request closed without merging**
