### PR TITLE
Various updates and fixes

### PR DESCRIPTION
**Pull request by d0k3**
This pull request contains only those features from my branch that are well tested and have been in there for some time. This is what it brings to the table (in short, longer descriptions in the commit texts):
- New BrahmaLoader with *hax 2.5 & good boot rates
- CakesROP submodule, so this can be compiled as well
- Completely rewritten menu system, features now have a parameters
- SD Decryptor, SeedDB Updater, NAND dump / restore, NAND file dump / restore features revised.
- Granular dumping / injecting of NAND partititions
- Granular dumping / injecting of various files on CTRNAND
- New SD Decryptor/Encryptor feature
- New NCCH Encryptor feature
- New CIA Decryptor features
- Multiple fixes and improvements

As always, if you want something organized or done differently, just let me know. As for the sheer mass of this pull request - that is in part due to me trying to make each commit as self contained as possible. However, it actually is a lot this time. If you would prefer smaller and more frequent pull reqests, I can try to do that.

### CODE REVIEW

**Comment by archshift** [comment]
I would definitely prefer smaller, self-contained pull requests, as reviewing and responding to the review with this set of highly diverse changes will be hard on both of us :)

**Comment by d0k3** [comment]
Alright, I'll try to do smaller and more frequent pull requests from now on. It's just that all that stuff needs to be properly tested before it is deemed worthy of a pull request, and because testers are sometimes rare, a lot of stuff gets accumulated. I also don't want to do pull request for features I don't think are finished. Still, a lot of the commits above are actually for revisions of older features, I know.

On the bright side, it looks a lot worse than it is (I think). While this pull request is not contained at all, the individual commits are as contained as it gets, and some of them are really very small.

**Comment by d0k3** [comment]
Alright, this is what I did...
- BrahmaAppInfo / VOODOO parameter: Added detailed description of BrahmaLoader parameters. This is squashed into https://github.com/d0k3/Decrypt9/commit/ccdcd28610d3e058e778c3c568f33686d5afc3f8
- CIA Decryptor (for GW): Renamed this to CIA Decryptor (CXI only), also removed all references to GW from the source code. This allows to still generate GW compatible files without advertising GW support. This is squashed into https://github.com/d0k3/Decrypt9/commit/28bd1bdfab378895df498af2b46a4e599c61c522
- game.c / SD Decryptor: Don't process backup and DSiWare folders. These two folders use a different kind of encryption. This is squashed into https://github.com/d0k3/Decrypt9/commit/062bb4855db50d524eb09b03b3bda7c51ed2ca86
- crypto.c / crypto.h: Moved all SHA related functionality to sha.c / sha.h. Also renamed crypto.c / crypto.h to aes.c / aes.h. (new commit)
- fs.c / fs.h (and some other places): Simplifed the working directory handling. InitFS(), FileOpen() and FileCreate() where slightly adapted to simplify the code. (new commit)
- game.c and some other files: Added some useful comments and improved the code style. (new commit).

This should adress everything you wrote before. I hope keeping that special CIA Decryptor function in there, with the new name, and all references to GW removed, is okay, if not just let me know! And I promise, following PRs will be much smaller :).

Wishing you a good start into the new year!

**Comment by archshift** [comment]
All in all it's pretty good!

You don't need to do this for this PR, but in the future, can you add doxygen comments to new functions that detail their usage, arguments, and return values? You've added so much functionality that I've started to lose track of what does what :)

Have a happy New Year yourself!

**Pull request merged**
