### PR TITLE
Add minimal Brahma loader and update scripts

### PR DESCRIPTION
**Pull request by d0k3**
Decrypt9.3DSX loader and Decrypt9.bin binary are built from one Makefile.

### CODE REVIEW

**Comment by archshift** [comment]
You're removing the ability to run this from the web browser. and introducing a lot of other unrelated changes.

**Comment by d0k3** [comment]
Yes, that's correct. To be honest, I didn't think about the web browser. Maybe you want to add it in a new fork, though, or something else from the pull request is usable to you.

**Comment by archshift** [comment]
I don't think it makes sense to fork brahma into the project, either. If you figure out a way to have a submodule of brahma work cleanly with the build system though, that would be a good addition.

Also, could you PR the addition of the `ncchinfo_tgen.py` separately?

**Comment by d0k3** [comment]
I'll do the PR for the new scripts later.

As for the Brahma submodule - do you think of something like a .BIN -> .3DSX converter, that could be integrated into the build process (without actually compiling it)? Basically there are two possibilities, (1) a .3DSX Brahma loader that loads the first .BIN file it finds in the directory or (2) a "stub", meaning a precompiled Brahma loader to which the actual .BIN file is copied into.

(1) is not all too different from how it works now. (2) would be similar to how most self extracting archives work, where the executable code is at the beginning and the archive is at the end of one self contained file. I hope I got that understandable.

Both possibilities would be platform independent, as all you'd need is a simple copy command, for (2) also with the possibility to copy two files into one. If you'd be interested in using that, I'll code that.

**Comment by archshift** [comment]
I'd rather not add binary files into the repo (the gateway launcher template is already annoying) at all, so I think if Brahma is going to be integrated at all it should be through a submodule.

It's also not like Brahma takes a particularly long time to compile or has any dependencies, so I don't see any issue with simply compiling it as part of the build process.

**Comment by d0k3** [comment]
Okay, understood. I'll see what I can do. This will be very similar to how it works now, only that Brahma wouldn't be integrated into Decrypt9.

**Pull request closed without merging**
