### PR TITLE
Various improvements and new features

### PR DESCRIPTION
**Pull request by d0k3**
This is a a big one:
- NCCH padgen now accepts basically any version ncchinfo.bin (even ones with UTF-16 filenames).
- NCCH padgen now correctly recognizes Secure3 and Secure4 crypto and reacts accordingly.
- NAND backups can be restored and NAND partitions injected.
- Dangerous features such as the above one have an unlock sequence to prevent accidential triggering.
- Any feature can now be processed on EmuNAND. The menu already contains ticket dumping, EmuNAND titlekey decryption and the two new features below.
- The 'seedsave' file (also known as the '00000000' file), which has the seeds needed for the seed crypto, can now be dumped from 9.6+ EmuNAND.
- The seeddb.bin file can now be created and updated. Also requires an 9.6+ EmuNAND.
- NCCH/NCSD files (such as .3DS rom dumps) can now be batch decrypted. Files go to /D9decrypt/
- Scrolling is enabled for debug output. This makes sense especially for features with much / long output.
- A new 'release' goal in the Makefile allows building all 4 other goals at once and moving their output into one 'release' folder alongside the Python scripts.

As always, if anything should be done differently or even be removed, just let me know. All the new features included have been properly tested, some for a very long time.

### CODE REVIEW

**Comment by archshift** [comment]
> NCCH/NCSD files (such as .3DS rom dumps) can now be batch decrypted. Files go to /D9decrypt/

I'll take a closer look later, but this could always be done by specifying multiple files to ncchinfo_gen.py...

**Comment by d0k3** [comment]
The real difference is that this will directly decrypt roms, without the need for xorpads and additional tools. Shouldn't take longer than NCCH padgen, as - for full decryption - the same amount of data is written to the SD card. If you only want to decrypt part of an NCSD/NCCH file (f.e. when converting to CIA), you're better off using NCCH padgen, though.

**Comment by archshift** [comment]
`decryptor.c` is getting pretty unfocused...do you think you could split up its different functions into different compilation units, such as `nand.c/h`, `title.c/h` (NCCH/NCSD), `titlekey.c/h`, etc.?

**Comment by d0k3** [comment]
I will think about a good concept for splitting up decryptor.c / .h and add a new commit to this pull request later. 

In the meantime:
- **The comment in  fs.h, for DirRead()** should be better understandable now. Note that I also added a DebugDirMake() function (seems to make sense for consistency) and slightly changed the debug output of DebugDirOpen() ("Opening [dir] .." -> "Opening dir [dir] ...") to better distinguish between this and opening files.
- **sdmmc.c / .h**: Taking a closer look at the source code it turned out that this was already fixed in the previous version of sdmmc.c / .h. The mistake is on my side, because I had previously used an even earlier version of it in my source code. No need for a full replacement. Note that I instead fixed some compiler warnings and moved delay.h / .s to the fatfs dir (because these only get used in sdmmc.c).
- **Replacing u32 with bool where appropriate**: I did the replacements, but there is no way this could still be squashed into the appropriate commits. I left it as an additional commit for now. I could also squash it into the last commit where main.c / decryptor.c was changed, which would be this one: https://github.com/d0k3/Decrypt9/commit/84a5e85651718099100caff698be1f12bbdcd99c

By the way, do you think it could make sense to make the release build goal the default? I understand this is also what gets auto-compiled in the nightly builds, and this way users would have all versions in one. EDIT: Just checked that again, and maybe I got that wrong. It would be nice to have the brahma and cakehax build goals among the nightly builds, too, though. EDIT2: I think I could make the needed changes to .travis.yml.

**Comment by d0k3** [comment]
I splitted it up, let me know what you think! Also note that I had to add a few functions and #defines to nand.c / nand.h to make it possible (all obvious from nand.h).

I am not perfectly happy with it. Everything is very much connected now, therefore making independent files was not possible. There is some stuff that could belong into multiple source files (think the Titlekey / NAND decryptor), but I had to choose, of course. I also do think that nand.c / nand.h is still pretty convoluted, but splitting that up further would require adding more functions to bridge the gap.

Anyways, let me know what you think!

**Comment by d0k3** [comment]
I've added one more commit. Didn't squash anything, just in cause you're already reviewing. If you think this is an improvement, I'll squash it into the previous one later, though.

I think the nandfat.c / .h files make sense, because I'm planning further file dumping / file injection features and nand.c / .h are less convoluted this way.

**Comment by archshift** [comment]
:ok_hand:

**Pull request merged**
